# Redis pod
# Using the official Redis image from Dockerhub
# Using the default  Redis port 6379
# info under the labels will be referenced within services

apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    app: demo-voting-app
  namespace: voting

spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379

