# Frontend result app of the votes
# Exposes port 80 which allows users to access it

apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-app-deployment
  labels:
    app: demo-voting-app
  namespace: voting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
  template:
    metadata:
      name: results-app-pod
      labels:
        name: results-app-pod
        app: demo-voting-app
      namespace: voting

    spec:
      containers:
        - name: results-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80