# Frontend result app of the votes
# Exposes port 80 which allows users to access it

apiVersion: v1
kind: Pod
metadata:
  name: results-app-pod
  labels:
    name: results-app-pod
    app: demo-voting-app
  namespace: voting

spec:
  containers:
    - name: results-app
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80