# Worker app of the overall voting application
# Written in .NET,
# This application will read votes from in-memory redis DB and update the persistent Postgres DB
# Does not expose any ports or not being called by other apps

apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-voting-app
  namespace: voting

spec:
  containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker

